### PR TITLE
Edstem

### PR DESCRIPTION
**Pull request by veerasekharbabu**

### CODE REVIEW

**Comment by iakremnev** [comment]
I'm sorry, what's this?

**Comment by veerasekharbabu** [comment]
As part of work around for the issue I altered few changes like creating
another package directory and updated the same on setup.py and other python
files.

**Comment by iakremnev** [comment]
I see that splitting into two packages helps the model to be served. I appreciate the effort!
However, this repository is made only for displaying a faulty serving scenario in https://github.com/bentoml/BentoML/issues/1621, so I'm not searching for a workaround.

**Comment by veerasekharbabu** [comment]
Thank you for the clarification.

**Pull request closed without merging**
